name: Version Update
on:
  push:
    branches: [ "main" ]
env:
  VERSION_NUM: 3.3.0
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: "main"
        persist-credentials: false 
        fetch-depth: 0
    - name: Update Version
      run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/btansy/versionWorkflowTest/releases \
        -f tag_name='v${{env.VERSION_NUM}}' \
        -f target_commitish='main' \
        -f name='v${{env.VERSION_NUM}}' \
        -f body='' \
        -F draft=false \
        -F prerelease=false \
        -F generate_release_notes=false 