name: Version Update
on:
  push:
    branches: [ "main" ]
jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/btansy/versionWorkflowTest/releases \
          -f tag_name='v1.0.0' \
          -f target_commitish='main' \
          -f name='v1.0.0' \
          -f body='Description of the release' \
          -F draft=false \
          -F prerelease=false \
          -F generate_release_notes=false 